import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/layout/footer";
import Navbar from "./components/layout/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FFT",
  description: "Generated by FFT Team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&family=Sofia+Sans:wght@500&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Navbar />
        <div className="mt-[6rem]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
